<?php

class Sphere extends GeometryFigure
{
    public function __construct()
    {
        $this->name = 'Сфера';
    }

    public function getName(): string
    {
        return $this->name;
    }

    public float $diametr = 0.0;


    public function getPerimeter(): float
    {
        return parent::getPerimeter(); // TODO: Change the autogenerated stub
    }

    public function getArea(): float
    {
        return parent::getArea(); // TODO: Change the autogenerated stub
    }
}